# Generated by Django 5.2.1 on 2025-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("suya", "Suya"),
                            ("akara", "Akara"),
                            ("puffpuff", "Puff Puff"),
                            ("noodles", "Noodles"),
                            ("shawarma", "Shawarma"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="food_photos/"),
                ),
            ],
        ),
    ]
